# Book settings
title: Demos for UCLAx Webinar Intro to Python
author: Benjamin J. Winjum
copyright: '2021'

# Launch button settings
repository:
  url: https://github.com/benjum/uclax-intro-python
  path_to_book: book
  branch: main

launch_buttons:
  binderhub_url: "https://mybinder.org"
  thebe: true

sphinx:
  config:
    html_extra_path: ['assets']

execute:
  execute_notebooks: 'off'

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution

